[versions]
activityCompose = "1.10.1"
activityComposeVersion = "1.10.1"
agp = "8.9.2"
androidxAppcompat = "1.6.1"
androidxCore = "2.0.1"
androidxJunit = "1.1.5"
androidxMaterial = "1.8.2"
appcompatVersion = "2.1.4"
arCore = "1.22.0"
arsceneview = "2.3.0"
arsceneviewVersion = "0.10.0"
compilerVersion = "4.16.0"
core = "1.49.0"
coreKtx = "1.16.0"
coreKtxVersion = "1.7.0"
coreVersion = "1.41.0"
espressoCoreVersion = "3.5.1"
filamentAndroid = "1.17.1"
firebaseAppcheckDebug = "18.0.0"
firebaseAppcheckPlayintegrity = "18.0.0"
firebaseAppcheckSafetynet = "17.0.0"
firebaseAuth = "23.2.1"
firebaseBom = "33.13.0"
firebaseStorageVersion = "20.2.1"
firebaseUiStorage = "8.0.2"
fragment = "2.13.0"
glideVersion = "4.16.0"
googleServices = "4.4.2"
gorisseSceneview = "1.21.3"
imagepicker = "2.1"
javaJwt = "3.10.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleRuntimeKtx = "2.9.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
material3 = "1.3.2"
materialVersion = "1.9.0"
okhttp = "4.9.1"
retrofit = "2.9.0"
firebaseCrashlyticsBuildtools = "3.0.3"
googleGmsGoogleServices = "4.4.2"
firebaseFirestore = "25.1.4"
firebaseStorage = "21.0.1"
firebaseAppcheckDebugTesting = "18.0.0"
sceneform = "version"
sceneformAndroidSdk = "1.20.4"
sceneformUxVersion = "1.15.0"
sceneformVersion = "1.23.0"
sceneview = "1.22.0"
scenecore = "1.0.0-alpha04"
assets = "1.17.1"
sceneviewAr = "1.18.1"
roomCompiler = "2.7.1"
sceneviewVersion = "2.3.0"
sceneformUx = "1.17.1"
media3CommonKtx = "1.7.1"
media3Exoplayer = "1.7.1"
supportCompat = "28.0.0"
runtimeAndroid = "1.8.2"
ui = "1.8.2"
uiVersion = "compose_ui_version"
kotlin = "2.0.21"
composeCompiler = "2.0.0"
cameraView = "1.4.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-activity-compose-v131 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-core-ktx-v170 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiVersion" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiVersion" }
androidx-ui-vcomposeuiversion = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
appcompat-v214 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
ar-core = { module = "io.github.sceneview:ar-core", version.ref = "arCore" }
arsceneview = { module = "io.github.sceneview:arsceneview", version.ref = "arsceneview" }
arsceneview-v0100 = { module = "io.github.sceneview:arsceneview", version.ref = "arsceneviewVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core = { module = "com.google.ar:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-v1410 = { module = "com.google.ar:core", version.ref = "coreVersion" }
filament-android = { module = "com.google.ar.sceneform:filament-android", version.ref = "filamentAndroid" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-appcheck = { module = "com.google.firebase:firebase-appcheck" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity", version.ref = "firebaseAppcheckPlayintegrity" }
firebase-appcheck-safetynet = { module = "com.google.firebase:firebase-appcheck-safetynet", version.ref = "firebaseAppcheckSafetynet" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage-v2021 = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorageVersion" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebaseUiStorage" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
google-firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug", version.ref = "firebaseAppcheckDebug" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gorisse-sceneform = { module = "com.gorisse.thomas.sceneform:sceneform", version.ref = "sceneform" }
gorisse-sceneview = { module = "com.gorisse.thomas.sceneview:sceneview", version.ref = "gorisseSceneview" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
firebase-appcheck-debug-testing = { group = "com.google.firebase", name = "firebase-appcheck-debug-testing", version.ref = "firebaseAppcheckDebugTesting" }
sceneform = { module = "com.google.ar.sceneform:sceneform", version.ref = "filamentAndroid" }
sceneform-android-sdk = { module = "io.github.sceneview:sceneform-android-sdk", version.ref = "sceneformAndroidSdk" }
sceneform-base = { module = "com.google.ar.sceneform:sceneform-base", version.ref = "filamentAndroid" }
sceneform-core = { module = "com.google.ar.sceneform:core", version.ref = "filamentAndroid" }
sceneform-sceneview = { module = "com.google.ar.sceneform:sceneview", version.ref = "filamentAndroid" }
sceneform-ux-v1150 = { module = "com.google.ar.sceneform.ux:sceneform-ux", version.ref = "sceneformUxVersion" }
sceneform-v1230 = { module = "com.gorisse.thomas.sceneform:sceneform", version.ref = "sceneformVersion" }
sceneview = { module = "io.github.sceneview:sceneview", version.ref = "sceneview" }
scenecore = { group = "androidx.xr.scenecore", name = "scenecore", version.ref = "scenecore" }
assets = { group = "com.google.ar.sceneform", name = "assets", version.ref = "assets" }
sceneview-ar = { module = "io.github.sceneview:sceneview-ar", version.ref = "sceneviewAr" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
sceneview-v230 = { module = "io.github.sceneview:sceneview", version.ref = "sceneviewVersion" }
sceneform-ux = { group = "com.google.ar.sceneform.ux", name = "sceneform-ux", version.ref = "sceneformUx" }
media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
support-compat = { module = "com.android.support:support-compat", version.ref = "supportCompat" }
ux = { module = "com.google.ar.sceneform:ux", version.ref = "filamentAndroid" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }